version: '2'
services:
  rest:
    build: .
    #image: silvanopessoa/rest:latest
    # ports: 
    #    - 8090:8090
    depends_on:
       - db
  db:
    image: postgres:9.6
    volumes:
       # Volume dos dados
       - ./dados:/var/lib/postgresql/data
       # Scripts
       - ./scripts:/scripts
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - web
    ports:
      - '8090:8090'