version: '3'
services:
  rest:
    image: docker-compose_rest
    ports:
       - 8089:8090
    depends_on:
       - db
  db:
    image: postgres:9.6
    volumes:
       # Volume dos dados
       - ./dados:/var/lib/postgresql/data
       # Scripts
       - ./scripts:/scripts
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql