FROM java:8
EXPOSE 8080
ADD ../target/spring-boot-sample-hateoas-2.0.1.RELEASE.jar spring-boot-sample-hateoas-2.0.1.RELEASE.jar
ENTRYPOINT ["java","-jar","spring-boot-sample-hateoas-2.0.1.RELEASE.jar"]

