version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - ./dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql