version: '3.2'
volumes:
  dados:
services:
  rest:
    image: docker-compose_rest
    ports:
       - 8090:8090
    depends_on:
       - db
  db:
    image: postgres:9.6
    ports:
       - 5432:5432
    volumes:
       # Volume dos dados
       - ./dados:/var/lib/postgresql/data
       # Scripts
       - ./scripts:/scripts
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql